Document: gerber-to-svg
Title: Debian gerber-to-svg Manual
Author: <insert document author here>
Abstract: This manual describes what gerber-to-svg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gerber-to-svg/gerber-to-svg.sgml.gz

Format: postscript
Files: /usr/share/doc/gerber-to-svg/gerber-to-svg.ps.gz

Format: text
Files: /usr/share/doc/gerber-to-svg/gerber-to-svg.text.gz

Format: HTML
Index: /usr/share/doc/gerber-to-svg/html/index.html
Files: /usr/share/doc/gerber-to-svg/html/*.html
